### ISSUE TITLE
shemaName

### ISSUE THREAD

**Issue by Rauno56** [voxpelli/node-connect-pg-simple#14] opened 2015-02-25 08:29 UTC
Introducing 'shemaName' was

1. Breaking change.
  * default went from 'session' to 'public.session' which means people who used search path to specify their shema, broke their code.
  * 'someTable' users had the same problem as above.
  * 'someSchema.someTable' users(who don't leave it in the hands of search path) now went to 'public.someSchema.someTable' which also breaks.
2. a bad idea IMO: Who needed it could have just specify tableName in the format of 'someSchema.someTable' on the other hand there is no way now to force this library to use search path because of the javascript coercion and `schemaName || 'public'` usage.

**Comment by voxpelli** [comment] 2015-02-25 08:37
The breaking change was unintended, I haven't used schemas in Postgres very extensively. What's your proposed solution going forward to solve this? Sounds like we should "unbreak" the breaking change by removing the `'public'` default?

**Comment by Rauno56** [comment] 2015-02-25 16:23
I'd actually like to hear from @richardwardza the intention behind the change. When we "unbreak" it now, we break it the other way.

However if we would just prepend the schema name to the tableName in constructor IF it is specified(no default) we'd be pretty much OK. People who don't know anything about the field would go back to the old way, and some, who, I-have-no-idea-but-in-some-reason need it, have the option.

**Comment by voxpelli** [comment] 2015-03-08 16:38
@Rauno56: I pushed a fix for it, the first PR (#10) should never have gotten through with that default – the purpose of it was to enable a clean configuration of schemas, not to change the default behavior.

Does this solve it for you? For @richardwardza as well perhaps?

**Comment by voxpelli** [comment] 2015-08-22 16:06
I will assume the problems that were had with regression and feature addition has been solved by the mentioned fixes as no further feedback has been given in a few months which would have been expected if there still were issues around this – so I will close this issue again now.

**Closed by voxpelli** 2015-08-22 16:06 UTC
