### ISSUE TITLE
fatal error: terminating connection due to a administrator command

### ISSUE THREAD

**Issue by eczajk1** [voxpelli/node-connect-pg-simple#40] opened 2016-12-12 13:17 UTC
I received this error over the weekend which crashed my app:

```
error: terminating connection due to administrator command
    at Connection.parseE (/usr/src/app/node_modules/connect-pg-simple/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/usr/src/app/node_modules/connect-pg-simple/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/usr/src/app/node_modules/connect-pg-simple/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:537:20)
```

I understand that something unusual has happened with postgres (see [this](https://www.postgresql.org/message-id/20100915125539.2CEFE167821F@mail.r3-gis.com) and [this](http://stackoverflow.com/questions/5787066/whats-the-cause-of-pgerror-fatal-terminating-connection-due-to-administrator)).  But is there a way I can prevent the error from bringing down the house?

**Comment by voxpelli** [comment] 2017-05-19 19:48
This sounds like a duplicate of #29 and while I know it's not a fun thing to get ones issue closed as a duplicate these many months later I do want to point you there now and should have done so earlier.

As said in #29 the error handling of `pg` has been somewhat complicated. This has probably changed in the new version of `pg` that is used now since version `4.0.0` so it may be time to look into the error handling once again.

**Closed by voxpelli** 2017-05-19 19:48 UTC
